greatbigcrane/project/urls.py
"""
Copyright 2010 Jason Chu, Dusty Phillips, and Phil Schalm

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls.defaults import *

urlpatterns = patterns('project.views',
        url('^$', 'list_projects', name="list_projects"),
        url('^(?P<project_id>\d+)/view/$', 'view_project', name="view_project"),
        url('^(?P<project_id>\d+)/edit/$', 'edit_project', name="edit_project"),
        url('^pip/(?P<project_id>\d+)/edit/$', 'edit_pip', name="edit_pip"),
        url('^add/$', 'add_project', name="add_project"),
        url('^(?P<project_id>\d+)/delete/$', 'delete_project', name="delete_project"),
        url('^(?P<project_id>\d+)/favourite/$', 'favourite_project', name="favourite_project"),
        url('^(?P<project_id>\d+)/notifications/$', 'project_notifications', name="project_notifications"),
        url('ajax', 'handle_ajax', name="projects_ajax")
        )

greatbigcrane/urls.py
"""
Copyright 2010 Jason Chu, Dusty Phillips, and Phil Schalm

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

handler500 # Pyflakes

urlpatterns = patterns('',
    url('^$', 'project.views.index', name="dashboard_url"),
    url('^about/$', 'project.views.about', name="about_url"),
    (r'^notifications/', include('notifications.urls')),
    (r'^projects/', include('project.urls')),
    (r'^recipes/', include('recipes.urls')),
    (r'^preferences/', include('preferences.urls')),
    (r'^jobs/', include('job_queue.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

greatbigcrane/project/models.py
"""
Copyright 2010 Jason Chu, Dusty Phillips, and Phil Schalm

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import os.path
from shutil import copyfile
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from buildout_manage.parser import buildout_parse

make_choice = lambda x: ([(p,p) for p in x])

class Project(models.Model):
    name = models.CharField(max_length=32)
    base_directory = models.CharField(max_length=512, unique=True)
    git_repo = models.CharField(max_length=512, blank=True, default='')
    description = models.TextField(blank=True,
            help_text="(Markdown syntax is supported)")
    project_type = models.CharField(max_length=9,
            choices=make_choice(["buildout", "pip"]))
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    test_status = models.BooleanField(default=False)
    favourite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("view_project", args=[self.id])

    def buildout_sections(self):
        '''Return sorted dictionary of buildout sections'''
        sections = self.buildout()
        # You may wonder why I'm returning items. I am too. For unknown
        # reasons, {{project.buildout_sections.items}} does not return a
        # correct value inside templates.
        return sections.items()

    def buildout_filename(self):
        '''Get the filename that holds the buildout configuration.'''
        return os.path.join(self.base_directory, 'buildout.cfg')

    def requirements_filename(self):
        '''Get the filename that holds the pip requirements.'''
        return os.path.join(self.base_directory, 'requirements.txt')

    def buildout(self):
        sections = buildout_parse(self.buildout_filename())
        return sections

    def is_django(self):
        if not self.pipproject:
            sections = self.buildout()
            for name, section in sections.items():
                if 'recipe' in section and section['recipe'] == 'djangorecipe':
                    return True
            return False
        else:
            return 'Django' in self.pipproject.requirements

    def github_url(self):
        '''If our repo is a github repo, provide a link to the
        github page.'''
        github = self.git_repo.find("github.com")
        if github > -1:
            url = self.git_repo[github:].replace(":", "/")
            if url.endswith(".git"):
                url = url[:-4]
            url = "http://%s" % url
        else:
            url = ""
        return url

    def prep_project(self):
        if self.project_type == "buildout":
            self.prep_buildout_project()
        elif self.project_type == "pip":
            self.prep_pip_project()

    def prep_buildout_project(self):
        if not os.path.isdir(self.base_directory):
            os.makedirs(self.base_directory)
        skeleton = [(os.path.join(settings.PROJECT_HOME, "../bootstrap.py"),
                os.path.join(self.base_directory, "bootstrap.py")),
            (os.path.join(settings.PROJECT_HOME, "../base_buildout.cfg"),
                os.path.join(self.base_directory, "buildout.cfg"))]
        for source, dest in skeleton:
            if not os.path.isfile(dest):
                copyfile(source, dest)

    def prep_pip_project(self):
        if not os.path.isdir(self.base_directory):
            os.makedirs(self.base_directory)
        PipProject.objects.create(project=self)

    def __unicode__(self):
        return self.name

# Possibly We could use inheritance here, but I think it would get messy with
# generating forms
class PipProject(models.Model):
    project = models.OneToOneField(Project)
    virtualenv_path = models.CharField(max_length=256,
            help_text="The directory the virtualenv is stored in.",
            default="venv/")
    test_command = models.CharField(max_length=128,
            blank=True,
            help_text="Command to run tests. Eg: py.test, nose, ./run_tests.py")

    @property
    def requirements(self):
        if os.path.exists(self.project.requirements_filename()):
            with open(self.project.requirements_filename()) as req_file:
                return req_file.read()
        return ""

greatbigcrane/project/forms.py
"""
Copyright 2010 Jason Chu, Dusty Phillips, and Phil Schalm

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import os.path
from django import forms

from project.models import Project, PipProject
from project.widgets import LineEditorWidget

class AddProjectForm(forms.ModelForm):
    class Meta:
        model = Project

    def clean_base_directory(self):
        value = self.cleaned_data['base_directory']
        return os.path.expanduser(value).strip()

    def clean_name(self):
        return self.cleaned_data['name'].strip()

    def clean_git_repo(self):
        return self.cleaned_data['git_repo'].strip()

    def clean_description(self):
        return self.cleaned_data['description'].strip()

class EditProjectForm(AddProjectForm):
    class Meta:
        model = Project
        exclude =("project_type",)

class PipProjectForm(forms.ModelForm):
    requirements = forms.CharField(widget=LineEditorWidget)

    class Meta:
        model = PipProject
        exclude = ("project",)

    def clean_virtualenv_path(self):
        if self.cleaned_data['virtualenv_path'] and not \
                self.cleaned_data['virtualenv_path'].endswith(os.path.sep):
            self.cleaned_data['virtualenv_path'] += os.path.sep
        return self.cleaned_data['virtualenv_path']

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance')
        initial = kwargs.setdefault('initial', {})
        initial['requirements'] = instance.requirements

        super(PipProjectForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        instance = super(PipProjectForm, self).save(*args, **kwargs)
        with open(instance.project.requirements_filename(), "w") as req_file:
            req_file.write(self.cleaned_data['requirements'])

greatbigcrane/project/views.py
"""
Copyright 2010 Jason Chu, Dusty Phillips, and Phil Schalm

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import os.path
import json
import datetime

from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.views.generic.list_detail import object_list
from django.views.generic.list_detail import object_detail
from django.views.generic.create_update import delete_object
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.forms.util import ErrorList

from job_queue.jobs import queue_job
from project.models import Project, PipProject
from project.forms import AddProjectForm, EditProjectForm, PipProjectForm
from preferences.models import Preference
from notifications.models import Notification

def index(request):
    '''We should move this to a different app. Possibly preferences, it's more generic.'''
    projects = Project.objects.filter(favourite=False).order_by('-updated_at')[:5]
    favourite_projects = Project.objects.filter(favourite=True).order_by('name')
    notifications = Notification.objects.exclude(dismissed=True)[:10]
    return render_to_response('index.html', RequestContext(request,
        {'project_list': projects,
            'favourite_project_list': favourite_projects,
            'notifications': notifications}))

def about(request):
    '''Also go to another app or flatpage...'''
    return render_to_response('about.html', RequestContext(request))

def list_projects(request):
    orderby = request.GET.get('orderby', 'name')
    projects = Project.objects.all().order_by(orderby)
    return object_list(request, projects,
            template_name="project/project_list.html",
            template_object_name="project",
            extra_context={'orderby': orderby})

def view_project(request, project_id):
    return object_detail(request, Project.objects.all(), object_id=project_id,
            template_object_name='project', extra_context={
                'notifications': Notification.objects.filter(
                    project=project_id,dismissed=False)[:10]})

def add_project(request):
    form = AddProjectForm(request.POST or None)
    if form.is_valid():
        try:
            base_dir = os.path.expanduser(form.cleaned_data['base_directory'])

            base_dir = base_dir.rstrip('/')
            if form.cleaned_data['git_repo']:
                target_dir = os.path.dirname(base_dir)
                if target_dir and not os.path.isdir(target_dir):
                    os.makedirs(target_dir)
                instance = form.save()
                queue_job("GITCLONE", project_id=instance.id)
            else:
                instance = form.save()
                instance.prep_project()
                if instance.project_type == "buildout":
                    queue_job("BOOTSTRAP", project_id=instance.id)

            return redirect(instance.get_absolute_url())

        except IOError as e:
            errors = form._errors.setdefault("base_directory", ErrorList())
            errors.append(u"An error occurred: " + str(e))

    base_url = Preference.objects.get_preference("projects_directory", '')

    return render_to_response("project/project_form.html",
            RequestContext(request, {'form': form, 'base_url': base_url}))

def edit_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    form = EditProjectForm(request.POST or None, instance=project)
    if form.is_valid():
        instance = form.save()
        return redirect(instance.get_absolute_url())

    base_url = Preference.objects.get_preference("projects_directory", '')

    return render_to_response("project/project_edit_form.html",
            RequestContext(request, {'form': form, 'base_url': base_url}))

def delete_project(request, project_id):
    return delete_object(request, model=Project, object_id=project_id,
            post_delete_redirect=reverse("list_projects"))

def favourite_project(request, project_id):
    project = Project.objects.get(pk=project_id)
    project.favourite=not project.favourite
    project.save()
    return handle_ajax(request)

# I'm wondering if pip doesn't deserve its own app
def edit_pip(request, project_id):
    project = get_object_or_404(Project, id=project_id,
            pipproject__isnull=False)
    pip = project.pipproject
    form = PipProjectForm(request.POST or None, instance=pip)
    if form.is_valid():
        instance = form.save()
        return redirect(project)

    return render_to_response("project/pip_edit_form.html",
            RequestContext(request, {'form': form}))

def project_notifications(request, project_id):
    project = Project.objects.get(pk=project_id)
    notifications = Notification.objects.filter(
            project=project_id,dismissed=False)[:10]
    return render_to_response("notifications/_notification_list.html",
            RequestContext(request, {'notifications': notifications,
                'project': project}))

#FIXME: I'm not sure what this method is doing, so I'm thinking it needs
# a less generic name.
def handle_ajax(request):
    if 'update' in request.POST:
        update = dict()
        d = json.loads(request.POST['update'])
        for k,v in d.items():
            if v == 'projects':
                update[k] = Project.objects.all().order_by(request.GET.get('orderby', 'name'))
            elif v == 'home-projects':
                update[k] = Project.objects.filter(favourite=False).order_by('-updated_at')[:5]
            elif v == 'favourite-projects':
                update[k] = Project.objects.filter(favourite=True).order_by('name')
            
            update[k] = render_to_string("project/_project_list.html", RequestContext(request,
                    {'project_list': update[k]}))
        
        return HttpResponse(json.dumps({'update': update}),content_type="application/json")
    else:
        return HttpResponse('fail')

greatbigcrane/templates/project/_form.html
<section>
  <label for="id_name">Management Type:</label>
  {{form.project_type.errors}}
  {{form.project_type}}
</section>
<section>
  <label for="id_name">Name:</label>
  {{form.name.errors}}
  {{form.name}}
</section>

<section>
  <label for="id_base_directory">Base Directory:</label>
  {{form.base_directory.errors}}
  {{form.base_directory}}
</section>

<section>
  <label for="id_git_repo">Git Repository:</label>
  {{form.git_repo.errors}}
  {{form.git_repo}}
</section>

<section>
  <label for="id_description">Description:</label>
  {{form.description.errors}}
  {{form.description.help_text}}
  {{form.description}}
</section>
  
  

greatbigcrane/templates/project/_project.html
<li id="project-{{project.id}}" class="clearfix">
  <div class="buttons clearfix">
    <a href="{% url favourite_project project.id %}" class="favourite{{project.favourite|yesno:' favourited,'}}" title="Favourite">Favourite</a>
    <a href="{% url schedule_buildout project.id %}" class="buildout" title="Run Buildout">Run Buildout</a>
    <a href="{% url schedule_test project.id %}" class="tests {{ project.test_status|yesno:'success,error' }}" title="Run Tests">Run Tests</a>
    <a href="{% url edit_project project.id %}" class="edit" title="Edit Project">Edit Project</a>
  </div>
  <h3>{{project.name}}</h3>
  <span>{{project.base_directory}}</span>
</li>

greatbigcrane/templates/project/_project_list.html
{% for project in project_list %}
  {% include 'project/_project.html' %}
{% endfor %}

greatbigcrane/templates/project/buildout_detail.html
{% load buildout_config %}
    <section class="buildout">
      <h2>Buildout Sections</h2>
      {% if not project.buildout_sections %}
        <p>No Buildout sections yet.</p>
      {% endif %}
      {% for name, section in project.buildout_sections %}
      <ul>
        <li class="clearfix">
          <a href="{% url edit_recipe project.id name %}" class="button right grey">Edit</a>
          <a href="{% url delete_recipe project.id name %}" class="button ajax right red confirm">Delete</a>
          <h3>{{name}}</h3>
          {% for key, value in section.items %}
          <ul>
            <li>{{key}} = {{value|configvalue}}</li>
          </ul>
          {% endfor %}
        </li>
      </ul>
      {% endfor %}
      <a href="{% url add_recipe project.id %}" class="left orange button orange">Add Recipe</a>
    </section>

greatbigcrane/templates/project/pip_detail.html
<a href="{% url edit_pip project.id %}" class="button right grey">Edit</a>

<p><strong>VirtualEnv:</strong> {{project.pipproject.virtualenv_path}}</p>
<p><strong>Test Command:</strong> {{project.pipproject.test_command}}</p>
<h2>Requirements</h2>
<p>
{{project.pipproject.requirements|linebreaksbr}}
</p>

greatbigcrane/templates/project/pip_edit_form.html
{% extends 'nosidebar.html' %}

{% block main %}
<form method="POST">
    {{form.media}}
    {{form.as_p}}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

greatbigcrane/templates/project/project_confirm_delete.html
{% extends 'nosidebar.html' %}

{% block contenttitle %}Delete {{object.name}}{% endblock %}

{% block main %}
<p>Are you sure you want to delete the {{object.name}} project?</p>
<form method="POST" class="clearfix">
  <input type="submit" value="Yes" class="red left"> 
  <a href="{{object.get_absolute_url}}" class="button orange left block">No</a>
</form>
{% endblock %}

greatbigcrane/templates/project/project_detail.html
{% extends 'sidebar.html' %}
{% load markup %}

{% block contenttitle %}{{project.name}}{% endblock %}

{% block main %}
  <div id="project-{{project.id}}" class="project">
    {% if project.git_repo %}
      <p><strong>Git Repository:</strong> {{project.git_repo}}</p>
    {% endif %}
    
    <p><strong>Directory:</strong> {{project.base_directory}}</p>
    
    {% if project.description %}
      <div class="description blocktext">{{project.description|markdown}}</div>
    {% endif %}
    
    {% if project.project_type == "buildout" %}
        {% include "project/buildout_detail.html" %}
    {% else %}
        {% include "project/pip_detail.html" %}
    {% endif %}
  </div>
{% endblock %}

{% block sidebar %}
  <div class="project">
  <section>
    <h2>Actions</h2>
    <div class="actions clearfix">
      <section class="clearfix">
        <a class="edit" href="{% url edit_project project.id %}" title="Edit Project">Edit Project</a>
        {% if project.project_type == "buildout" %}
        <a class="edit_cfg ajax" href="{% url edit_buildout project.id %}" title="Edit Buildout">Edit Buildout</a>
        {% endif %}
        <a class="delete confirm" href="{% url delete_project project.id %}" title="Delete Project">Delete Project</a>
      </section>
      
      <section class="clearfix">
        {% if project.project_type == "buildout" %}
          <a class="bootstrap ajax" href="{% url schedule_bootstrap project.id %}" title="Bootstrap Buildout">Bootstrap Buildout</a>
          <a class="buildout ajax" href="{% url schedule_buildout project.id %}" title="Run Buildout">Buildout</a>
        {% else %}
          <a class="virtualenv ajax" href="{% url schedule_virtualenv project.id %}" title="Build Virtualenv">Build Virtualenv</a>
          <a class="pip_install ajax" href="{% url schedule_pip_install project.id %}" title="Pip Install">Pip Install</a>
        {% endif %}
        <a class="tests ajax {{ project.test_status|yesno:'success,error' }}" href="{% url schedule_test project.id %}" title="Run Tests">Test</a>
      </section>
      
      {% if project.github_url and project.git_repo %}<section class="clearfix">{% endif %}      
        {% if project.github_url %}
          <a class="github" href="{{project.github_url}}" title="View on Github">View on Github</a>
        {% endif %}
        {% if project.git_repo %}
          <a class="pull ajax" href="{% url schedule_pull project.id %}" title="Git Pull">Git Pull</a>
        {% endif %}
      {% if project.github_url and project.git_repo %}</section>{% endif %}
      
      {% if project.is_django %}
        <section class="clearfix">
          <a class="syncdb ajax" href="{% url schedule_syncdb project.id %}" title="SyncDB">Syncdb</a>
        {# Ideally this would only show up if we knew south was installed #}
          <a class="migrate ajax" href="{% url schedule_migrate project.id %}" title="Migrate">Migrate</a>
          <a class="startapp" href="{% url startapp project.id %}" title="Start App">Start App</a>
        </section>
      {% endif %}
    </div>
  </section>
  <section>
    <h2>Notifications</h2>
    <ul class="tests live">
      {% for notification in notifications %}
        {% include 'notifications/_notification.html' %}
      {% endfor %}
    </ul>
  </section>
</div>
{% endblock %}

greatbigcrane/templates/project/project_edit_form.html
{% extends "project/project_form.html" %}

{% block contenttitle %}Edit project "{{form.instance.name}}"{% endblock %}

{% block submit_command %}Save Project{% endblock %}
{% block cancel_url %}{% url view_project form.instance.id %}{% endblock %}
{% block scripts %}{% endblock %}

greatbigcrane/templates/project/project_form.html
{% extends 'nosidebar.html' %}

{% block contenttitle %}Add A Project{% endblock %}

{% block main %}
<form method="post" class="clearfix">
  {% csrf_token %}
  {% include 'project/_form.html' %}
  <div class="buttons clearfix">
    <input type="submit" value="{% block submit_command %}Create Project{% endblock %}" class="left blue">
    <a href="{% block cancel_url %}{% url list_projects %}{% endblock %}" class="button left orange">Cancel</a>
  </div>
</form>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
  $('#id_name').change(function() {
    $('#id_base_directory').val('{{base_url}}' + slugify($('#id_name').val()) + "/");
  });
</script>
{% endblock %}

greatbigcrane/templates/project/project_list.html
{% extends 'sidebar.html' %}

{% block contenttitle %}Projects{% endblock %}

{% block main %}
<div class="projects">
  <form action="/projects/" method="get">
    <p class="inline">
    <label for="id_orderby">Order By:</label>
      <select name="orderby" class="autosubmit">
        <option {% if orderby == 'name' or orderby == '' %}selected="selected"{% endif %} value="name">Name</option>
        <option {% if orderby == '-updated_at' %}selected="selected"{% endif %} value="-updated_at">Last Updated</option>
        <option {% if orderby == '-test_status' %}selected="selected"{% endif %} value="-test_status">Test Status</option>
      </select>
    </p>
    <ul class="projects" id="project-list">
      {% include 'project/_project_list.html' %}
    </ul>
  </form>
</div>
{% endblock %}

{% block sidebar %}
<a class="button right orange" href="{% url add_project %}">Add Project</a>
{% endblock %}

greatbigcrane/templates/project/single_project.html
<li id="project-{{project.id}}">
  <div class="buttons">
    <a href="{{project.get_absolute_url}}favourite" class="favourite">Favourite</a>
    <a href="#play" class="play">Play</a>
    <a href="{{project.get_absolute_url}}" class="settings">Settings</a>
  </div>
  <h3>{{project.name}}</h3>
  <span>{{project.base_directory}}</span>
</li>